### PR TITLE
Add neat UI

### PR DESCRIPTION
**Pull request by BLNDLYBLV**
Added a neat UI in pure css, changed every pages, 
Could not make it responsive because i have very less knowledge in  making responsive sites
Hope you like it 😇

### CODE REVIEW

**Comment by BLNDLYBLV** [comment]
image

**Comment by BLNDLYBLV** [comment]
image

**Comment by BLNDLYBLV** [comment]
Can you please add hacktoberfest topic to your repo, plsss

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Can you please add hacktoberfest topic to your repo, plsss

@BLNDLYBLV Yes, added the label

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Added a neat UI in pure css, changed every pages,
> Could not make it responsive because i have very less knowledge in making responsive sites
> Hope you like it 😇

issue1
issue2
These files UI were affected by the changes you made. Can you work them out? I will merge this PR once that's done.
@BLNDLYBLV

**Comment by BLNDLYBLV** [comment]
but changing only these files will be odd right because my ui is really different from the existing one in every pages
image

**Comment by SubhamKarmakar24** [comment]
> 
> 
> but changing only these files will be odd right because my ui is really different from the existing one in every pages
> image

Hey @BLNDLYBLV , the files have been combined. You can add the CSS now so that it will work on all the game modes. I will merge the PR soon after that

**Comment by BLNDLYBLV** [comment]
Sure i'll change it accordingly

**Comment by BLNDLYBLV** [comment]
Hey I changed my code according to the conflicts, if any queries comment here @SubhamKarmakar24

**Comment by BLNDLYBLV** [comment]
Hey @SubhamKarmakar24 , I have put a lot of effort doing this UI, So please consider merging the pull request
It will be really helpful for me with the hacktoberfest

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Hey @SubhamKarmakar24 , I have put a lot of effort doing this UI, So please consider merging the pull request
> It will be really helpful for me with the hacktoberfest

Yes sure

**Pull request merged**
